version: '4.3'

services:
  api:
    build: .
    container_name: api
    ports:
      - "3408:3408"
    depends_on:
      - database
    volumes:
      - .:/app
    networks:
      - diet_control

  database:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - diet_control

networks:
  diet_control:
    driver: bridge
