services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - .:/app
      - /app/node_modules
    user: node
    command: pnpm dev

  database:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /var/diet_control/mysql
